# Generated by Django 5.0.7 on 2025-02-22 15:00

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 22, 15, 0, 25, 988322, tzinfo=datetime.timezone.utc)),
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_type', models.CharField(choices=[('HOME_LOAN', 'Home Loan'), ('PERSONAL_LOAN', 'Personal Loan'), ('EDUCATION_LOAN', 'Education Loan'), ('CAR_LOAN', 'Car Loan'), ('GOLD_LOAN', 'Gold loan'), ('OTHERS', 'Others')], max_length=50)),
                ('loan_tenure', models.IntegerField(default=1)),
                ('loan_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('loan_status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2025, 2, 22, 15, 0, 25, 988322, tzinfo=datetime.timezone.utc))),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.user_reg')),
            ],
        ),
    ]
