# Generated by Django 5.0.7 on 2025-02-22 15:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0002_alter_transactions_timestamp_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 22, 15, 4, 44, 155017, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 22, 15, 4, 44, 155017, tzinfo=datetime.timezone.utc)),
        ),
    ]
