# Generated by Django 5.0.7 on 2025-02-23 05:05

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0007_alter_loan_timestamp_alter_transactions_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billpayment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bank.user_reg'),
        ),
        migrations.AlterField(
            model_name='loan',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 23, 5, 5, 39, 690794, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 23, 5, 5, 39, 689054, tzinfo=datetime.timezone.utc)),
        ),
    ]
