# Generated by Django 5.0.7 on 2025-02-23 05:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0008_alter_billpayment_user_alter_loan_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='billpayment',
            name='bill_status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid')], default='PENDING', max_length=20),
        ),
        migrations.AlterField(
            model_name='loan',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 23, 5, 36, 15, 816283, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 23, 5, 36, 15, 816283, tzinfo=datetime.timezone.utc)),
        ),
    ]
