# Generated by Django 5.0.7 on 2025-02-24 17:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0009_billpayment_bill_status_alter_loan_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='employment_type',
            field=models.CharField(default='', max_length=90),
        ),
        migrations.AlterField(
            model_name='loan',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 17, 38, 2, 394743, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 24, 17, 38, 2, 394743, tzinfo=datetime.timezone.utc)),
        ),
    ]
