# Generated by Django 5.0.7 on 2025-03-01 09:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0010_loan_employment_type_alter_loan_timestamp_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_reg',
            name='Role',
            field=models.CharField(choices=[('User', 'User'), ('Manager', 'Manager'), ('Admin', 'Admin')], default='User', max_length=100),
        ),
        migrations.AlterField(
            model_name='loan',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 1, 9, 26, 12, 783204, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 1, 9, 26, 12, 783204, tzinfo=datetime.timezone.utc)),
        ),
    ]
