# Generated by Django 5.0.7 on 2025-03-22 13:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0011_user_reg_role_alter_loan_timestamp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 13, 37, 53, 340731, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 22, 13, 37, 53, 340731, tzinfo=datetime.timezone.utc)),
        ),
    ]
