# Generated by Django 5.0.7 on 2025-03-23 15:37

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0013_alter_loan_timestamp_alter_transactions_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 23, 15, 37, 24, 875254, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 23, 15, 37, 24, 875254, tzinfo=datetime.timezone.utc)),
        ),
    ]
