# Generated by Django 5.0.7 on 2025-03-28 17:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0015_alter_loan_timestamp_alter_transactions_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 17, 12, 14, 499449, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 28, 17, 12, 14, 499449, tzinfo=datetime.timezone.utc)),
        ),
    ]
