# Generated by Django 5.0.7 on 2025-03-29 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0016_alter_loan_timestamp_alter_transactions_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_reg',
            name='Pan',
        ),
        migrations.RemoveField(
            model_name='user_reg',
            name='aadhaar',
        ),
        migrations.AlterField(
            model_name='loan',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 3, 16, 42, 986533, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 3, 16, 42, 985531, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user_reg',
            name='Role',
            field=models.CharField(choices=[('User', 'User'), ('Admin', 'Admin')], default='User', max_length=100),
        ),
    ]
