# Generated by Django 5.0.7 on 2025-03-29 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank', '0017_remove_user_reg_pan_remove_user_reg_aadhaar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 5, 40, 38, 886877, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 29, 5, 40, 38, 886877, tzinfo=datetime.timezone.utc)),
        ),
    ]
